# Puerto para desarrollo
server.port=8081
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

# Configuración de base de datos - DESARROLLO
spring.datasource.url=jdbc:mariadb://localhost:3306/nocheapp?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración JPA - DESARROLLO
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.use_sql_comments=true

# Configuración de logging - DESARROLLO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.com.schoolDays.noche_app=DEBUG
logging.level.org.springframework.web=DEBUG

# Configuración de desarrollo
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0

#spring.main.allow-circular-references=true